// Generated by CoffeeScript 1.4.0

/*
	richisCore v0.1
	@Author @richistron
	@description coffeScript core
	@License MIT
*/


(function() {
  var ItemLiModel, ItemView, itemM, selector, view;

  ItemLiModel = Backbone.Model.extend({
    urlRoot: "/feeds.php?getRss=feeds",
    getData: function(e) {
      var conf;
      e.preventDefault();
      conf = this.feedConf(this);
      return view.$el.feeds(conf);
    },
    feedConf: function(element) {
      element = element;
      console.log(element);
      return {
        feeds: {
          "feedUrl": element.get("feedUrl")
        },
        onComplete: function(data) {
          element.set("feedData", data);
          return console.log(element.get("feedData"));
        }
      };
    }
  });

  itemM = new ItemLiModel({
    id: "richistron",
    feedUrl: "http://blog.richistron.com/feeds/posts/default",
    feedTitle: "El blog del richistron",
    feedLogo: "/img/cats/120x120.jpg",
    feedDescription: "When programming in any language there are certain common errors that everyone makes as they mature and evolve their ...",
    feedLink: "http://blog.richistron.com/",
    feedAutor: "Ricardo Rivas",
    feedData: {}
  });

  ItemView = Backbone.View.extend({
    tagName: "div",
    className: "box",
    initialize: function() {
      return this.model.on("change", this.render, this);
    },
    events: {
      "click a": "getData"
    },
    getData: _.once(function(e) {
      return this.model.getData(e);
    }),
    render: function() {
      var data;
      data = this.model.toJSON();
      return this.$el.html(this.template(data));
    },
    template: _.template("			<article>				<header>                            					<h1>						<a href='#<%= id %>'>							<%= feedTitle %>						</a>					</h1>				<div class='thumb'>					<img src='<%= feedLogo %>' alt='<%= id %>_logo'/>				</div>				<p>					<%= feedDescription %>					<a href='<%= feedLink %>' class='readmore'>Leer más</a>								</p>     				<span class='author'> Author: <strong> <%= feedAutor %> </strong></span>                   						</article>		")
  });

  view = new ItemView({
    model: itemM
  });

  view.render();

  selector = "#sitios";

  $(document).ready(function() {
    return $(selector).html(function() {
      return view.el;
    });
  });

}).call(this);
