// Generated by CoffeeScript 1.4.0

/*
	richisCore v0.1
	@Author @richistron
	@description coffeScript core
	@License MIT
*/


(function() {
  var ItemLiModel, ItemView, itemM, view;

  ItemLiModel = Backbone.Model.extend({
    urlRoot: "/feeds.php?getRss=feeds"
  });

  itemM = new ItemLiModel({
    id: "richistron",
    feedUrl: "http://blog.richistron.com/feeds/posts/default",
    feedTitle: "El blog del richistron",
    feedLogo: "/img/cats/120x120.jpg",
    feedDescription: "When programming in any language there are certain common errors that everyone makes as they mature and evolve their ...",
    feedLink: "http://blog.richistron.com/",
    feedAutor: "Ricardo Rivas"
  });

  ItemView = Backbone.View.extend({
    tagName: "article",
    render: function() {
      var data;
      data = this.model.toJSON();
      return this.$el.html(this.template(data));
    },
    template: _.template("			<header>                            				<h1>					<a href='#<%= id %>'>						<%= feedTitle %>					</a>				</h1>			<div class='thumb'>				<img src='<%= feedLogo %>' alt='<%= id %>_logo'/>			</div>			<p>				<%= feedDescription %>				<a href='<%= feedLink %>' class='readmore'>Leer más</a>							</p>     			<span class='author'> Author: <strong> <%= feedAutor %> </strong></span>                   					")
  });

  view = new ItemView({
    model: itemM
  });

  view.render();

  $(document).ready(function() {
    return $("#sitios .box").html(function() {
      return view.el;
    });
  });

}).call(this);
